name: "Build workflow"

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: "Rust Cache"
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ hashFiles('**/Cargo.lock') }}

      - name: "Install Nix"
        uses: cachix/install-nix-action@v14.1

      - name: "Cache nix stuff"
        uses: cachix/cachix-action@v10
        with:
          name: wasm-hello
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Build"
        run: nix-shell --run "./cli build --release" build.nix

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
